---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj4-ryanj4-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/ryanj4-gateway-gitops
